---
- name: deploy the CS image software stack
  hosts: localhost
  connection: local
  become: true

  vars:
    install_packages:
      - apt-clone
      - apt-transport-https
      - atom
      - build-essential
      - clang
      - clang-format
      - cmake
      - cmake-extras
      - code
      - codeblocks
      - curl
      - emacs
      - exfat-fuse
      - exfat-utils
      - fish
      - firefox
      - gcc
      - gcc-multilib
      - geany
      - git
      - google-chrome-stable
      - guake
      - htop
      - libc6-dev
      - libfuse-dev
      - libfuse2
      - libssl-dev
      - nnn
      - p7zip-full
      - pass
      - screen
      - sshpass
      - sublime-text
      - sysstat
      - tcl
      - tcsh
      - terminator
      - tmpreaper
      - tmux
      - ubuntu-desktop
      - ubuntu-minimal
      - ubuntu-restricted-extras
      - ubuntu-standard
      - unrar
      - unzip
      - update-motd
      - valgrind
      - vim
      - xterm
      - xvfb
      - xz-utils
      - zlib1g-dev
      - zsh


    delete_packages:
      - eclipse
      - gnome-initial-setup
      - gnome-software
      - transmission-common
      - transmission-gtk
      - ubuntu-software
      - ubuntu-web-launchers

  tasks:

    - name: Get aptitude for upgrade
      apt: pkg=aptitude state=present

    - name: Safe system upgrade via aptitude
      apt: upgrade=safe

    - name: import the atom apt key
      apt_key:
         id: 0A0FAB860D48560332EFB581B75442BBDE9E3B09
         url: https://packagecloud.io/AtomEditor/atom/gpgkey
         state: present

    - name: install atom repository
      apt_repository:
        repo: deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main
        state: present
        update_cache: yes

    - name: import the Google Chrome apt key
      apt_key:
         id: 4CCA1EAF950CEE4AB83976DCA040830F7FAC5991
         url: https://dl-ssl.google.com/linux/linux_signing_key.pub
         state: present

    - name: install Google Chrome repository
      apt_repository:
        repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
        state: present
        update_cache: yes

    - name: import the sublime-text apt key
      apt_key:
         id: 1EDDE2CDFC025D17F6DA9EC0ADAE6AD28A8F901A
         url: https://download.sublimetext.com/sublimehq-pub.gpg
         state: present

    - name: install sublime-text repository
      apt_repository:
        repo: deb https://download.sublimetext.com/ "apt/stable/"
        state: present
        update_cache: yes

    - name: import the vscode apt key
      apt_key:
         id: BC528686B50D79E339D3721CEB3E94ADBE1229CF
         url: https://packages.microsoft.com/keys/microsoft.asc
         state: present

    - name: install vscode repository
      apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
        state: present
        update_cache: yes

    - name: install base packages
      apt:
        pkg: "{{ install_packages }}"
        dpkg_options: force-confold,force-confdef
        state: latest
        update_cache: yes
        cache_valid_time: 604800

    - name: remove some packages
      apt:
        pkg: "{{ delete_packages }}"
        dpkg_options: force-confold,force-confdef
        state: absent
        update_cache: yes
        cache_valid_time: 604800
